In [1]:
import pandas as pd

df = pd.read_csv('long_091826.csv').set_index('peptide')

In [3]:
lasv = df.loc[df['species'] == 'Mammarenavirus lassaense']

In [5]:
lasv = lasv.reset_index()

In [35]:
lasv.head(2)

,peptide,individual,z_score,rpk,sequence,species,genus,family,protein_std,accession,cohort,category,reactive
0,AHC95546.1|polymerase|Mammarenavirus_lassaense...,C-109-3_4_E7,-0.655047,0.263884,TDDAVVAEDDIEQLIYQFKRASPILRFLYSDIEGEEDRKNVQVVKE,Mammarenavirus lassaense,Mammarenavirus,Arenaviridae,polymerase,AHC95546.1,SL,Household contact,False
1,AHC95546.1|polymerase|Mammarenavirus_lassaense...,C-109-3_4_E7,-0.735745,0.900343,RESTSRSITEDFFYSNYQNGVVPSHISSVLDMGQGILHNTSDFYAL,Mammarenavirus lassaense,Mammarenavirus,Arenaviridae,polymerase,AHC95546.1,SL,Household contact,False

In [57]:
peps_mean = lasv.groupby(['cohort', 'protein_std', 'peptide', 'sequence'])['reactive'].mean().sort_values(ascending=False).reset_index()

In [58]:
peps_mean['tile_num'] = peps_mean['peptide'].str.split('_').str[-1]

In [71]:
peps_mean.head(1)

,cohort,protein_std,peptide,sequence,reactive,tile_num
0,SL,nucleoprotein,AZI96407.1|nucleoprotein|Mammarenavirus_lassae...,KVGTTGSNKSLQSAGFPAGLTYSQLMTLKDSMMQLDPSAKTWIDIE,0.380353,16

## now for each tile_num, I want the most seroprevalent peptide

In [69]:
top_peps_max = peps_mean.loc[
    peps_mean.groupby(['protein_std', 'tile_num'])['reactive'].idxmax(), 
    ['protein_std', 'tile_num', 'peptide', 'sequence', 'reactive']
].reset_index(drop=True).sort_values(by='reactive', ascending=False)
#want the row index where reactive is highest

In [77]:
top_peps_max = top_peps_max.rename(columns={'reactive': 'fraction_reactive'})

In [79]:
top_peps_max['fraction_reactive'] = top_peps_max['fraction_reactive'].round(2)

In [81]:
top_peps_max.to_csv('most_seroprevalent_LASV_peptides_per_tile_num.csv', index=False)