In [11]:
import pandas as pd

df = pd.read_csv('long_091826.csv')
meta = pd.read_csv('lassa_library_sequences_species_standardized_070726_ICTV_corrected.csv')

### for all species

In [32]:
pep_hits = df.groupby(['species', 'genus', 'family'])['sequence'].nunique().rename('n')
denom = meta.groupby(['species', 'genus', 'family'])['sequence'].nunique()

missing = set(pep_hits.index) - set(denom.index)
assert not missing, f"species in hits but not in meta: {sorted(missing)[:10]}"

out = pd.DataFrame({
    "n_hits": pep_hits.reindex(denom.index, fill_value=0), 
    "n_in_library": denom,
})

out["pct_hits"] = (out["n_hits"] / out["n_in_library"] * 100).round(2)

#filter coverage -- how well is represented in lib
MIN_LIB = 20
out = out[out["n_in_library"] >= MIN_LIB].sort_values("pct_hits", ascending=False)

print(f"{len(denom)} species, {len(out)} with >= {MIN_LIB} peptides in library")

441 species, 412 with >= 20 peptides in library

In [34]:
out.loc['Mammarenavirus lassaense']

                             n_hits  n_in_library  pct_hits
genus          family
Mammarenavirus Arenaviridae      76          4494      1.69

In [35]:
out.sort_values(by=['pct_hits', 'n_hits'], ascending=False).head(100)

,,,n_hits,n_in_library,pct_hits
species,genus,family,,,
S2-like reptarenavirus,Reptarenavirus,Arenaviridae,3,43,6.98
Palma virus,Phlebovirus,Phenuiviridae,2,32,6.25
Gbagroube virus,Arenavirus,Arenaviridae,2,36,5.56
Menekre virus,Arenavirus,Arenaviridae,2,44,4.55
Phlebovirus ambeense,Phlebovirus,Phenuiviridae,7,170,4.12
...,...,...,...,...,...
Orthonairovirus zirkuense,Orthonairovirus,Nairoviridae,5,246,2.03
Mammarenavirus ganziense,Mammarenavirus,Arenaviridae,4,198,2.02
Phlebovirus candiruense,Phlebovirus,Phenuiviridae,10,499,2.00
Hartmanivirus haartmani,Hartmanivirus,Arenaviridae,4,204,1.96
Limestone Canyon virus,Orthohantavirus,Hantaviridae,3,155,1.94

In [43]:
out.groupby('genus')['pct_hits'].head(3).reset_index().sort_values(by=['genus', 'pct_hits'], ascending=[True,False]).head(50)

,species,genus,family,pct_hits
41,Actinovirus triacanthodis,Actinovirus,Hantaviridae,1.91
50,Actinovirus bernense,Actinovirus,Hantaviridae,1.75
78,Actinovirus halieutaeae,Actinovirus,Hantaviridae,0.00
67,Agnathovirus eptatreti,Agnathovirus,Hantaviridae,1.17
72,Alphavirus chikungunya,Alphavirus,Togaviridae,0.59
26,Antennavirus hirsutum,Antennavirus,Arenaviridae,2.72
28,Antennavirus striale,Antennavirus,Arenaviridae,2.53
69,Antennavirus salmonis,Antennavirus,Arenaviridae,1.02
2,Gbagroube virus,Arenavirus,Arenaviridae,5.56
3,Menekre virus,Arenavirus,Arenaviridae,4.55
61,Arenavirus sp.,Arenavirus,Arenaviridae,1.41
43,Bandavirus kismaayoense,Bandavirus,Phenuiviridae,1.89
44,Bandavirus bhanjanagarense,Bandavirus,Phenuiviridae,1.85
46,Bandavirus guertuense,Bandavirus,Phenuiviridae,1.82
24,Cuevavirus lloviuense,Cuevavirus,Filoviridae,2.78
70,Dianlovirus menglaense,Dianlovirus,Filoviridae,1.00
5,Hartmanivirus quadrati,Hartmanivirus,Arenaviridae,3.94
31,Hartmanivirus helvetiae,Hartmanivirus,Arenaviridae,2.36
35,Hartmanivirus brazilense,Hartmanivirus,Arenaviridae,2.17
17,Henipavirus nipahense,Henipavirus,Paramyxoviridae,3.16
39,Henipavirus hendraense,Henipavirus,Paramyxoviridae,1.92
51,Henipavirus ghanaense,Henipavirus,Paramyxoviridae,1.73
79,Homo sapiens,Homo,Hominidae,0.00
34,Innmovirus hailarense,Innmovirus,Arenaviridae,2.21
10,Ixovirus gakugsaense,Ixovirus,Phenuiviridae,3.60
53,Ixovirus yichunense,Ixovirus,Phenuiviridae,1.69
71,Loanvirus brunaense,Loanvirus,Hantaviridae,0.90
12,Mammarenavirus kwanzaense,Mammarenavirus,Arenaviridae,3.45
20,Mammarenavirus loeiense,Mammarenavirus,Arenaviridae,2.92
23,Mammarenavirus caliense,Mammarenavirus,Arenaviridae,2.78
8,Mobatvirus quezonense,Mobatvirus,Hantaviridae,3.80
58,Mobatvirus xuansonense,Mobatvirus,Hantaviridae,1.54
65,Mobatvirus dakrongense,Mobatvirus,Hantaviridae,1.27
52,Morbillivirus hominis,Morbillivirus,Paramyxoviridae,1.70
59,Norwavirus sp.,Norwavirus,Nairoviridae,1.50
80,Norwavirus beijiense,Norwavirus,Nairoviridae,0.00
32,Ocetevirus paratemnopterygis,Ocetevirus,Nairoviridae,2.35
76,Olpivirus lactucae,Olpivirus,Konkoviridae,0.00
30,Orthoebolavirus taiense,Orthoebolavirus,Filoviridae,2.41
42,Orthoebolavirus sudanense,Orthoebolavirus,Filoviridae,1.90
54,Orthoebolavirus restonense,Orthoebolavirus,Filoviridae,1.69
36,Chimeric Tick-borne encephalitis virus/Dengue ...,Orthoflavivirus,Flaviviridae,2.10
49,Orthoflavivirus zikaense,Orthoflavivirus,Flaviviridae,1.76
56,Orthoflavivirus denguei,Orthoflavivirus,Flaviviridae,1.56
6,Orthohantavirus mamorense,Orthohantavirus,Hantaviridae,3.90
11,Yakeshi virus,Orthohantavirus,Hantaviridae,3.57
13,Fusong virus,Orthohantavirus,Hantaviridae,3.39
45,Orthomarburgvirus marburgense,Orthomarburgvirus,Filoviridae,1.83
15,Orthonairovirus thiaforaense,Orthonairovirus,Nairoviridae,3.23
19,Wufeng shrew orthonairovirus 2,Orthonairovirus,Nairoviridae,3.01

In [ ]:
pep_hits_norm.sort_values(ascending=False).head(30)

species
Phlebovirus sp. PAN 483391                      10.00
Amga virus                                      10.00
Mopeia Lassa virus reassortant 29                8.33
Rodent Mammarenavirus                            7.69
S2-like reptarenavirus                           6.98
Muraenolepis arenavirus                          6.90
Palma virus                                      6.25
Gbagroube virus                                  5.56
Arenavirus H0030026                              4.55
Menekre virus                                    4.55
Phlebovirus ambeense                             4.12
Hartmanivirus quadrati                           3.94
Orthohantavirus mamorense                        3.90
Uukuvirus dabieshanense                          3.88
Mobatvirus quezonense                            3.80
Hemidactylus frenatus arenavirus                 3.74
Sclerotinia sclerotiorum phlebo-like virus 1     3.67
Ixovirus gakugsaense                             3.60
Phlebovirus riograndense                         3.59
Yakeshi virus                                    3.57
Ponticelli I virus                               3.51
Grapi virus                                      3.45
Mammarenavirus kwanzaense                        3.45
Fusong virus                                     3.39
Necocli virus                                    3.39
Parahenipavirus daeryongense                     3.33
Hantavirus Jurong TJK/06(RT50)                   3.33
Phlebovirus wuxiangense                          3.29
Orthonairovirus thiaforaense                     3.23
Thottimvirus imjinense                           3.21
dtype: float64

### more LASV

In [ ]:
lasv = df.loc[df['species'] == 'Mammarenavirus lassaense']

meta_lasv = meta.loc[meta['species'] == 'Mammarenavirus lassaense']

In [ ]:
lasv_protein_std = lasv.groupby('protein_std')['peptide'].nunique()
lasv_protein_std

protein_std
glycoprotein      5
nucleoprotein     7
polymerase       62
z protein         2
Name: peptide, dtype: int64

In [ ]:
meta_group = meta_lasv.groupby('protein_std')['seq_id'].size()

In [ ]:
meta_group

protein_std
glycoprotein      228
nucleoprotein     255
polymerase       3696
z protein         315
Name: seq_id, dtype: int64

In [ ]:
for protein in meta_group.keys():
    print(f'total peptides belonging to {protein}', meta_group[protein])
    total_peps = meta_group[protein]
    react_peps = lasv_protein_std[protein]
    print(f'total reac peps for {protein}', react_peps)

    frac = react_peps / total_peps
    frac = round(frac * 100, 1)

    print(f'% of reactive peps for {protein}', frac)

total peptides belonging to glycoprotein 228
total reac peps for glycoprotein 5
% of reactive peps for glycoprotein 2.2
total peptides belonging to nucleoprotein 255
total reac peps for nucleoprotein 7
% of reactive peps for nucleoprotein 2.7
total peptides belonging to polymerase 3696
total reac peps for polymerase 62
% of reactive peps for polymerase 1.7
total peptides belonging to z protein 315
total reac peps for z protein 2
% of reactive peps for z protein 0.6